import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  jobs: defineTable({
    title: v.string(),
    slug: v.string(),
    status: v.union(v.literal("open"), v.literal("running"), v.literal("complete"), v.literal("removed")),
    kind: v.union(v.literal("inference"), v.literal("rollout"), v.literal("logprob"), v.literal("eval")),
    priority: v.union(v.literal("low"), v.literal("normal"), v.literal("high")),
    createdBy: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    removedAt: v.optional(v.number()),
    targetRollouts: v.number(),
    completedRollouts: v.number(),
    activeClaims: v.number(),
    rewardUsd: v.optional(v.number()),
    lineageParentId: v.optional(v.id("jobs")),
    model: v.string(),
    weights: v.optional(v.string()),
    promptSet: v.array(v.string()),
    schemaVersion: v.string(),
    jobSpec: v.string(),
  }).index("by_status", ["status"]).index("by_slug", ["slug"]),
  claims: defineTable({
    jobId: v.id("jobs"),
    workerName: v.string(),
    workerContact: v.optional(v.string()),
    status: v.union(v.literal("active"), v.literal("submitted"), v.literal("released")),
    claimedAt: v.number(),
    updatedAt: v.number(),
    targetRollouts: v.number(),
    submittedRollouts: v.number(),
    notes: v.optional(v.string()),
  }).index("by_job", ["jobId"]).index("by_worker", ["workerName"]),
  submissions: defineTable({
    jobId: v.id("jobs"),
    claimId: v.optional(v.id("claims")),
    workerName: v.string(),
    createdAt: v.number(),
    rolloutCount: v.number(),
    artifactUri: v.optional(v.string()),
    artifactText: v.optional(v.string()),
    baseTrajectoryUri: v.optional(v.string()),
    logprobsUri: v.optional(v.string()),
    notes: v.optional(v.string()),
  }).index("by_job", ["jobId"]),
});
