export type CalibrationRow = { task_id: string; band?: string; score?: number | null; [key: string]: unknown };
export type CalibrationOptions = { model?: string | null; split?: string | null; threshold?: number; minSample?: number; generatedAt?: string; source: { path: string; sha256: string } };
export type BandStatus = "saturated" | "measurable" | "insufficient_sample";
export type BandVerdict = "block_training" | "invest" | "caution";
export type BandSummary = { tasks: number; scored: number; mean_score: number | null; exact_1: number; zero: number; headroom: number | null; ci: { lower: number; upper: number } | null; low_sample: boolean; saturated: boolean; saturated_lower_bound: boolean; status: BandStatus; verdict: BandVerdict };
export type CalibrationReport = { schema_version: "understudy.difficulty_calibration.v1"; generated_at: string; source_run: { path: string; sha256: string }; model: string | null; split: string | null; threshold: number; min_sample: number; overall: { tasks: number; scored: number; mean: number | null; headroom: number | null }; bands: Record<string, BandSummary>; saturated_bands: string[]; measurable_bands: string[]; gate: { worth_investing: boolean; reason: string } };

const mean = (xs: readonly number[]) => xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null;
function ci(xs: readonly number[], avg: number | null) { if (avg === null) return null; if (xs.length < 2) return { lower: avg, upper: avg }; const variance = xs.reduce((s, x) => s + (x - avg) ** 2, 0) / (xs.length - 1); const margin = 1.96 * Math.sqrt(variance / xs.length); return { lower: Math.max(0, avg - margin), upper: Math.min(1, avg + margin) }; }
function options(o: Pick<CalibrationOptions, "threshold" | "minSample">) { const threshold = o.threshold ?? .95; const minSample = o.minSample ?? 10; if (!Number.isFinite(threshold) || threshold <= 0 || threshold > 1) throw new Error("threshold must be a finite number in (0, 1]"); if (!Number.isInteger(minSample) || minSample < 1) throw new Error("minSample must be a positive integer"); return { threshold, minSample }; }
function row(v: unknown): CalibrationRow | null { if (!v || typeof v !== "object" || Array.isArray(v)) return null; const x = v as Record<string, unknown>; if (typeof x.task_id !== "string" || !x.task_id) return null; return { task_id: x.task_id, ...(typeof x.band === "string" && x.band ? { band: x.band } : {}), ...(typeof x.score === "number" && Number.isFinite(x.score) ? { score: x.score } : x.score === null ? { score: null } : {}) }; }

export function resolveBand(value: unknown): string { const x = row(value); return x?.band ?? "unknown"; }
export function summarizeBands(rows: readonly unknown[], supplied: Pick<CalibrationOptions, "threshold" | "minSample"> = {}): Record<string, BandSummary> { const { threshold, minSample } = options(supplied); const buckets = new Map<string, { tasks: number; scores: number[] }>(); for (const value of rows) { const x = row(value); if (!x) continue; const band = resolveBand(x); const b = buckets.get(band) ?? { tasks: 0, scores: [] }; b.tasks++; if (typeof x.score === "number" && x.score >= 0 && x.score <= 1) b.scores.push(x.score); buckets.set(band, b); } return Object.fromEntries([...buckets].sort(([a], [b]) => a.localeCompare(b)).map(([band, b]) => { const average = mean(b.scores); const interval = ci(b.scores, average); const saturated = average !== null && average >= threshold; const low = b.scores.length < minSample; const status = low ? "insufficient_sample" : saturated ? "saturated" : "measurable"; return [band, { tasks: b.tasks, scored: b.scores.length, mean_score: average, exact_1: b.scores.filter(x => x === 1).length, zero: b.scores.filter(x => x === 0).length, headroom: average === null ? null : 1 - average, ci: interval, low_sample: low, saturated, saturated_lower_bound: interval !== null && interval.lower >= threshold, status, verdict: status === "saturated" ? "block_training" : status === "measurable" ? "invest" : "caution" }]; })); }
export function buildCalibrationReport(rows: readonly unknown[], o: CalibrationOptions): CalibrationReport { if (!o.source?.path || !/^[a-f0-9]{64}$/i.test(o.source.sha256)) throw new Error("source.path and a 64-character source.sha256 are required"); const { threshold, minSample } = options(o); const bands = summarizeBands(rows, o); const valid = rows.map(row).filter((x): x is CalibrationRow => x !== null); const scores = valid.map(x => x.score).filter((x): x is number => typeof x === "number" && x >= 0 && x <= 1); const average = mean(scores); const saturated = Object.entries(bands).filter(([, x]) => x.status === "saturated").map(([x]) => x); const measurable = Object.entries(bands).filter(([, x]) => x.status === "measurable").map(([x]) => x); const worth = measurable.length > 0; return { schema_version: "understudy.difficulty_calibration.v1", generated_at: o.generatedAt ?? new Date().toISOString(), source_run: o.source, model: o.model ?? null, split: o.split ?? null, threshold, min_sample: minSample, overall: { tasks: valid.length, scored: scores.length, mean: average, headroom: average === null ? null : 1 - average }, bands, saturated_bands: saturated, measurable_bands: measurable, gate: { worth_investing: worth, reason: worth ? `Investable headroom remains in: ${measurable.join(", ")}.` : "No sufficiently sampled measurable band has headroom." } }; }
